gps_topic_name: /novatel_rear/odom
imu_topic_name: /xbow440_node/imu/data

initial_heading_deg: 999.0 # value greater than 360 means automatic initialization using course

gps_course_min_speed: 0.5

imu_time_step: 0.01

queue_size: 1

# Initial state estimate uncertainty (0 -> use covariance from first GPS measurement)
# initial_position_std_dev: 1.0
# initial_velocity_std_dev: 0.1

initial_attitude_std_dev: 0.035

# Measurement uncertainty (0 -> use covariance from odom message TO DO)


gps_position_updates: true
gps_velocity_updates: true


# IMU noise (0 -> use covariance from imu message TO DO)
random_walk_accelerometer: 0.034
bias_instability_accelerometer: 0.0003
bias_offset_accelerometer: 0.1
random_walk_gyroscope: 0.001
bias_instability_gyroscope: 0.00001
bias_offset_gyroscope: 0.01

input_rotation_matrix: [ 1, 0, 0,
                         0, 1, 0,
                         0, 0, 1]

# offset from IMU to antenna 
longitudinal_antenna_offset: 0.0
lateral_antenna_offset: 0.0
vertical_antenna_offset: -0.91


