initial_heading_deg: 999.0 # value > 360 means automatic initialization using course

# Initial state estimate uncertainty (0 -> use covariance from first GPS measurement)
initial_position_std_dev: 0.0
initial_velocity_std_dev: 0.0

initial_attitude_std_dev: 0.035

# Measurement uncertainty (0 -> use covariance from odom message TO DO)
position_std_dev: 0.0
velocity_std_dev: 0.0

gps_position_updates: true
gps_velocity_updates: true


# IMU noise (0 -> use covariance from imu message)
random_walk_accelerometer: 0.03
bias_instability_accelerometer: 0.0001
bias_offset_accelerometer: 0.01
random_walk_gyroscope: 0.000465 
bias_instability_gyroscope: 0.000001
bias_offset_gyroscope: 0.001

input_rotation_matrix: [ 1,  0,  0,
                         0,  1,  0,
                         0,  0,  1]

longitudinal_antenna_offset: 0.0
lateral_antenna_offset: 0.0
vertical_antenna_offset: 0.0


